//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.12 at 09:36:12 PM IST 
//


package exameval.domain.feedback.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="questionType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="totalMarks" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="questionFeddback" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="feedbackSubQuestions">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="feedbackSubQuestion" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="feedback" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="subQuestionId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="marks" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="questionId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "questionType",
    "totalMarks",
    "questionFeddback",
    "feedbackSubQuestions"
})
@XmlRootElement(name = "feedback")
public class Feedback {

    @XmlElement(required = true)
    protected String questionType;
    protected int totalMarks;
    protected List<String> questionFeddback;
    @XmlElement(required = true)
    protected Feedback.FeedbackSubQuestions feedbackSubQuestions;
    @XmlAttribute(name = "questionId")
    protected String questionId;
	
	public void addQuestionFeedback(String feedback){
		if(questionFeddback==null)
			questionFeddback = new ArrayList<>();
		
		questionFeddback.add(feedback);
	}

    /**
     * Gets the value of the questionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuestionType() {
        return questionType;
    }

    /**
     * Sets the value of the questionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuestionType(String value) {
        this.questionType = value;
    }

    /**
     * Gets the value of the totalMarks property.
     * 
     */
    public int getTotalMarks() {
        return totalMarks;
    }

    /**
     * Sets the value of the totalMarks property.
     * 
     */
    public void setTotalMarks(int value) {
        this.totalMarks = value;
    }

    /**
     * Gets the value of the questionFeddback property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the questionFeddback property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQuestionFeddback().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getQuestionFeddback() {
        if (questionFeddback == null) {
            questionFeddback = new ArrayList<String>();
        }
        return this.questionFeddback;
    }

    /**
     * Gets the value of the feedbackSubQuestions property.
     * 
     * @return
     *     possible object is
     *     {@link Feedback.FeedbackSubQuestions }
     *     
     */
    public Feedback.FeedbackSubQuestions getFeedbackSubQuestions() {
        return feedbackSubQuestions;
    }

    /**
     * Sets the value of the feedbackSubQuestions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Feedback.FeedbackSubQuestions }
     *     
     */
    public void setFeedbackSubQuestions(Feedback.FeedbackSubQuestions value) {
        this.feedbackSubQuestions = value;
    }

    /**
     * Gets the value of the questionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuestionId() {
        return questionId;
    }

    /**
     * Sets the value of the questionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuestionId(String value) {
        this.questionId = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="feedbackSubQuestion" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="feedback" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="subQuestionId" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="marks" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "feedbackSubQuestion"
    })
    public static class FeedbackSubQuestions {

        protected List<Feedback.FeedbackSubQuestions.FeedbackSubQuestion> feedbackSubQuestion;

        /**
         * Gets the value of the feedbackSubQuestion property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the feedbackSubQuestion property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFeedbackSubQuestion().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Feedback.FeedbackSubQuestions.FeedbackSubQuestion }
         * 
         * 
         */
        public List<Feedback.FeedbackSubQuestions.FeedbackSubQuestion> getFeedbackSubQuestion() {
            if (feedbackSubQuestion == null) {
                feedbackSubQuestion = new ArrayList<Feedback.FeedbackSubQuestions.FeedbackSubQuestion>();
            }
            return this.feedbackSubQuestion;
        }
        

        public void addFeedbackSubQuestion(Feedback.FeedbackSubQuestions.FeedbackSubQuestion feedbackSubQuestion) {
        	if (this.feedbackSubQuestion == null) {
        		this.feedbackSubQuestion = new ArrayList<Feedback.FeedbackSubQuestions.FeedbackSubQuestion>();
            }
        	
        	this.feedbackSubQuestion.add(feedbackSubQuestion);
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="feedback" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *       &lt;attribute name="subQuestionId" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="marks" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "feedback"
        })
        public static class FeedbackSubQuestion {

            protected List<String> feedback;
            @XmlAttribute(name = "subQuestionId")
            protected String subQuestionId;
            @XmlAttribute(name = "marks")
            protected Integer marks;

            /**
             * Gets the value of the feedback property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the feedback property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getFeedback().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getFeedback() {
                if (feedback == null) {
                    feedback = new ArrayList<String>();
                }
                return this.feedback;
            }
        	
        	public void addFeedback(String feedback){
        		if(this.feedback==null)
        			this.feedback = new ArrayList<>();
        		
        		this.feedback.add(feedback);
        	}

            /**
             * Gets the value of the subQuestionId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSubQuestionId() {
                return subQuestionId;
            }

            /**
             * Sets the value of the subQuestionId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSubQuestionId(String value) {
                this.subQuestionId = value;
            }

            /**
             * Gets the value of the marks property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getMarks() {
                return marks;
            }

            /**
             * Sets the value of the marks property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setMarks(Integer value) {
                this.marks = value;
            }

        }

    }

}
